### ISSUE TITLE
Unable to process an input with single measure

### ISSUE THREAD

**Issue by napulen** [apmcleod/harmonic-inference#69]
Running the pretrained model on an `mxl` file with a single measure results in the following crash:

```python
Loading pieces:   0%|                                                                             | 0/1 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/napulen/harmonic-inference/annotate.py", line 327, in <module>
    pieces = load_pieces(xml=ARGS.xml, input_path=ARGS.input, specific_id=ARGS.id)
  File "/home/napulen/harmonic-inference/harmonic_inference/utils/data_utils.py", line 152, in load_pieces
    pieces = [
  File "/home/napulen/harmonic-inference/harmonic_inference/utils/data_utils.py", line 153, in <listcomp>
    get_score_piece_from_music_xml(
  File "/home/napulen/harmonic-inference/harmonic_inference/data/piece.py", line 943, in get_score_piece_from_music_xml
    measures_df = get_measures_df_from_music21_score(m21_score)
  File "/home/napulen/harmonic-inference/harmonic_inference/data/piece.py", line 779, in get_measures_df_from_music21_score
    ts_epoch = Fraction(list(m21_score.measureOffsetMap().keys())[1] / 4)
IndexError: list index out of range
Loading pieces:   0%|                                                                             | 0/1 [00:00<?, ?it/s]
```

Can confirm that the same input with an additional measure that repeats the last chord was successfully processed.

**Comment by apmcleod** [comment]
Hello @napulen, can you please send me the two example files? The one that fails and the one with an additional measure. This should be a simple fix.
