### ISSUE TITLE
`utils.remove_repeats()` eats up the measures table

### ISSUE THREAD

**Issue by johentsch** [apmcleod/harmonic-inference#74]
Trying out annotating with forced labels, first attempt with a single piece. Here's the aggregated data: [146_wer.zip](https://github.com/apmcleod/harmonic-inference/files/11368245/146_wer.zip)

_Edit: It seems to be happening only in this special case where dealing with a single piece._

**Steps to reproduce**

Extract to `corpus_data` and run 

```
python annotate.py -i ../corpus_data/ -o output --label-type dcml --checkpoint checkpoints-beat-best -l annotate.log
```

**Error**

Occurred with the current `1.0.0` version on the `output` branch:

```python-traceback
Traceback (most recent call last):
  File "~/harmonic-inference/annotate.py", line 376, in <module>
    pieces = load_pieces(xml=ARGS.xml, input_path=ARGS.input, specific_id=ARGS.id)
  File "~/harmonic-inference/harmonic_inference/utils/data_utils.py", line 125, in load_pieces
    files_df, measures_df, chords_df, notes_df = load_clean_corpus_dfs(input_path)
  File "~/harmonic-inference/harmonic_inference/data/corpus_reading.py", line 202, in load_clean_corpus_dfs
    notes_df = cu.add_note_offsets(notes_df, measures_df)
  File "~/harmonic-inference/harmonic_inference/utils/corpus_utils.py", line 291, in add_note_offsets
    if isinstance(measures.iloc[0]["next"], list) or isinstance(measures.iloc[0]["next"], tuple):
  File "~/miniconda3/envs/harmony/lib/python3.10/site-packages/pandas/core/indexing.py", line 1073, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "~/miniconda3/envs/harmony/lib/python3.10/site-packages/pandas/core/indexing.py", line 1625, in _getitem_axis
    self._validate_integer(key, axis)
  File "~/miniconda3/envs/harmony/lib/python3.10/site-packages/pandas/core/indexing.py", line 1557, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
```

**Origin**

I could trace back the error to [corpus_reading.py#L140](https://github.com/apmcleod/harmonic-inference/blob/output/harmonic_inference/data/corpus_reading.py#L140). After this call, `measures_df` is empty.

**Comment by apmcleod** [comment]
Can confirm that I can reproduce this issue. Will look into it Friday or Monday.

**Comment by apmcleod** [comment]
This should be fixed now. Please check and close.
