### ISSUE TITLE
`annotate.py` fails in the presence of `chords.tsv`

### ISSUE THREAD

**Issue by johentsch** [apmcleod/harmonic-inference#75]
Calling `python annotate.py -i corpus_data -o corpus_data --label-type dcml --checkpoint checkpoints-beat-best -l annotate.log` on this [corpus_data.zip](https://github.com/apmcleod/harmonic-inference/files/11371077/corpus_data.zip) works only if one removes `chord.tsv`, otherwise it fails with

```pathon-traceback
Traceback (most recent call last):
  File "~/harmonic-inference/annotate.py", line 376, in <module>
    pieces = load_pieces(xml=ARGS.xml, input_path=ARGS.input, specific_id=ARGS.id)
  File "~/harmonic-inference/harmonic_inference/utils/data_utils.py", line 169, in load_pieces
    pieces = [
  File "~/harmonic-inference/harmonic_inference/utils/data_utils.py", line 170, in <listcomp>
    get_score_piece_from_data_frames(
  File "~/harmonic-inference/harmonic_inference/data/piece.py", line 970, in get_score_piece_from_data_frames
    non_repeated_mask = get_reduction_mask(
  File "~/harmonic-inference/harmonic_inference/data/piece.py", line 75, in get_reduction_mask
    mask = np.full(len(inputs), True, dtype=bool)
TypeError: len() of unsized object
```

NB: `chords.tsv` contains exactly one chord label per piece.

**Comment by apmcleod** [comment]
Can confirm that I can reproduce this issue. Will look into it Friday or Monday.

**Comment by apmcleod** [comment]
This should be fixed now. Please check and close when you get a chance.
