### ISSUE TITLE
Aggregation seems to be hard-coded to a present `harmonies` folder

### ISSUE THREAD

**Issue by johentsch** [apmcleod/harmonic-inference#78]
**Goal**

Using the library to infer harmonies on five Bach chorales, forcing a few labels.

**Setup**

Two working directories:
* `~/corpus_data` for data, containing the folder `MS3` with these five MuseScore files [MS3.zip](https://github.com/apmcleod/harmonic-inference/files/11655467/MS3.zip)
* `~/harmonic_inference` with this repo checked out to `output`

1. Extract data using `ms3==1.2.9` in `~/corpus_data`: `ms3 extract -a -M -N -X -L`
   * `-M` => folder `measures`
   * `-N` => folder `notes`
   * `-X` => folder `harmonies` (DCML label, excluding forced labels such as `Key=C` or `!K`)
   * `-L` => folder `labels` (all labels, but without splitting DCML labels into their feature columns)
2. From the `~/harmonic_inference` folder, aggregate `python aggregate_corpus_data.py -i ~/bach_chorales/ -o ~/corpus_data`

**Bug 1**

If we omit `-X` from the extraction command (we want to include all forces), we get the warning ["No files found to aggregate."](https://github.com/apmcleod/harmonic-inference/blob/output/harmonic_inference/data/corpus_reading.py#L302) because the corpus_reading module seems to depend on the presence of a `harmonies` folder.

But even with `-X` included, only four files make it into the aggregated data: "132 Kyrie, Gott Vater in Ewigkeit" is missing because the `harmonies` folder has no file for it (no DCML label included). The label `Key=e` can be found only in the corresponding "labels/132 Kyrie, Gott Vater in Ewigkeit.tsv".

**Bug 2**

As a workaround we could try to solve the issue by replacing the files in `harmonies` with those from `labels` (or extract accordingly using `ms3 extract -a -M -N -L harmonies`). Indeed, the aggregated `chords.tsv` now includes all labels, but it is now missing the feature columns for the DCML labels. The inference command `python annotate.py --label-type dcml --checkpoint checkpoints-beat-best -l annotate.log -i ~/corpus_data/inference -o ~/corpus_data/inference --forces ~/corpus_data/MS3` therefore fails with

```python-traceback
Traceback (most recent call last):
  File "~/harmonic-inference/annotate.py", line 376, in <module>
    pieces = load_pieces(xml=ARGS.xml, input_path=ARGS.input, specific_id=ARGS.id)
  File "~/harmonic-inference/harmonic_inference/utils/data_utils.py", line 125, in load_pieces
    files_df, measures_df, chords_df, notes_df = load_clean_corpus_dfs(input_path)
  File "~/harmonic-inference/harmonic_inference/data/corpus_reading.py", line 147, in load_clean_corpus_dfs
    chords_df.loc[(chords_df.numeral == "@none") | chords_df.numeral.isnull()].index
  File "/home/hentsche/miniconda3/envs/harmony/lib/python3.10/site-packages/pandas/core/generic.py", line 5902, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'numeral'
```

**Comment by apmcleod** [comment]
There is an additional (undocumented...) parameter to aggregate.py, `--notes-only`, which should make it include files with no harmony labels. Does using it solve the issue?
